/* automatically generated by rust-bindgen 0.72.1 */

pub type VkDeviceSize = u64;
pub type VkFlags = u32;
#[repr(C)]
#[derive(Copy, Clone)]
pub struct VkBuffer_T {
    _unused: [u8; 0],
}
pub type VkBuffer = *mut VkBuffer_T;
#[repr(C)]
#[derive(Copy, Clone)]
pub struct VkImage_T {
    _unused: [u8; 0],
}
pub type VkImage = *mut VkImage_T;
#[repr(C)]
#[derive(Copy, Clone)]
pub struct VkInstance_T {
    _unused: [u8; 0],
}
pub type VkInstance = *mut VkInstance_T;
#[repr(C)]
#[derive(Copy, Clone)]
pub struct VkPhysicalDevice_T {
    _unused: [u8; 0],
}
pub type VkPhysicalDevice = *mut VkPhysicalDevice_T;
#[repr(C)]
#[derive(Copy, Clone)]
pub struct VkDevice_T {
    _unused: [u8; 0],
}
pub type VkDevice = *mut VkDevice_T;
#[repr(C)]
#[derive(Copy, Clone)]
pub struct VkQueue_T {
    _unused: [u8; 0],
}
pub type VkQueue = *mut VkQueue_T;
#[repr(C)]
#[derive(Copy, Clone)]
pub struct VkCommandBuffer_T {
    _unused: [u8; 0],
}
pub type VkCommandBuffer = *mut VkCommandBuffer_T;
#[repr(C)]
#[derive(Copy, Clone)]
pub struct VkDeviceMemory_T {
    _unused: [u8; 0],
}
pub type VkDeviceMemory = *mut VkDeviceMemory_T;
#[repr(C)]
#[derive(Copy, Clone)]
pub struct VkRenderPass_T {
    _unused: [u8; 0],
}
pub type VkRenderPass = *mut VkRenderPass_T;
#[repr(C)]
#[derive(Copy, Clone)]
pub struct VkFramebuffer_T {
    _unused: [u8; 0],
}
pub type VkFramebuffer = *mut VkFramebuffer_T;
#[repr(C)]
#[derive(Copy, Clone)]
pub struct VkPipelineCache_T {
    _unused: [u8; 0],
}
pub type VkPipelineCache = *mut VkPipelineCache_T;
pub const VkImageLayout_VK_IMAGE_LAYOUT_UNDEFINED: VkImageLayout = 0;
pub const VkImageLayout_VK_IMAGE_LAYOUT_GENERAL: VkImageLayout = 1;
pub const VkImageLayout_VK_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL: VkImageLayout = 2;
pub const VkImageLayout_VK_IMAGE_LAYOUT_DEPTH_STENCIL_ATTACHMENT_OPTIMAL: VkImageLayout = 3;
pub const VkImageLayout_VK_IMAGE_LAYOUT_DEPTH_STENCIL_READ_ONLY_OPTIMAL: VkImageLayout = 4;
pub const VkImageLayout_VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL: VkImageLayout = 5;
pub const VkImageLayout_VK_IMAGE_LAYOUT_TRANSFER_SRC_OPTIMAL: VkImageLayout = 6;
pub const VkImageLayout_VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL: VkImageLayout = 7;
pub const VkImageLayout_VK_IMAGE_LAYOUT_PREINITIALIZED: VkImageLayout = 8;
pub const VkImageLayout_VK_IMAGE_LAYOUT_DEPTH_READ_ONLY_STENCIL_ATTACHMENT_OPTIMAL: VkImageLayout =
    1000117000;
pub const VkImageLayout_VK_IMAGE_LAYOUT_DEPTH_ATTACHMENT_STENCIL_READ_ONLY_OPTIMAL: VkImageLayout =
    1000117001;
pub const VkImageLayout_VK_IMAGE_LAYOUT_DEPTH_ATTACHMENT_OPTIMAL: VkImageLayout = 1000241000;
pub const VkImageLayout_VK_IMAGE_LAYOUT_DEPTH_READ_ONLY_OPTIMAL: VkImageLayout = 1000241001;
pub const VkImageLayout_VK_IMAGE_LAYOUT_STENCIL_ATTACHMENT_OPTIMAL: VkImageLayout = 1000241002;
pub const VkImageLayout_VK_IMAGE_LAYOUT_STENCIL_READ_ONLY_OPTIMAL: VkImageLayout = 1000241003;
pub const VkImageLayout_VK_IMAGE_LAYOUT_READ_ONLY_OPTIMAL: VkImageLayout = 1000314000;
pub const VkImageLayout_VK_IMAGE_LAYOUT_ATTACHMENT_OPTIMAL: VkImageLayout = 1000314001;
pub const VkImageLayout_VK_IMAGE_LAYOUT_RENDERING_LOCAL_READ: VkImageLayout = 1000232000;
pub const VkImageLayout_VK_IMAGE_LAYOUT_PRESENT_SRC_KHR: VkImageLayout = 1000001002;
pub const VkImageLayout_VK_IMAGE_LAYOUT_VIDEO_DECODE_DST_KHR: VkImageLayout = 1000024000;
pub const VkImageLayout_VK_IMAGE_LAYOUT_VIDEO_DECODE_SRC_KHR: VkImageLayout = 1000024001;
pub const VkImageLayout_VK_IMAGE_LAYOUT_VIDEO_DECODE_DPB_KHR: VkImageLayout = 1000024002;
pub const VkImageLayout_VK_IMAGE_LAYOUT_SHARED_PRESENT_KHR: VkImageLayout = 1000111000;
pub const VkImageLayout_VK_IMAGE_LAYOUT_FRAGMENT_DENSITY_MAP_OPTIMAL_EXT: VkImageLayout =
    1000218000;
pub const VkImageLayout_VK_IMAGE_LAYOUT_FRAGMENT_SHADING_RATE_ATTACHMENT_OPTIMAL_KHR:
    VkImageLayout = 1000164003;
pub const VkImageLayout_VK_IMAGE_LAYOUT_VIDEO_ENCODE_DST_KHR: VkImageLayout = 1000299000;
pub const VkImageLayout_VK_IMAGE_LAYOUT_VIDEO_ENCODE_SRC_KHR: VkImageLayout = 1000299001;
pub const VkImageLayout_VK_IMAGE_LAYOUT_VIDEO_ENCODE_DPB_KHR: VkImageLayout = 1000299002;
pub const VkImageLayout_VK_IMAGE_LAYOUT_ATTACHMENT_FEEDBACK_LOOP_OPTIMAL_EXT: VkImageLayout =
    1000339000;
pub const VkImageLayout_VK_IMAGE_LAYOUT_TENSOR_ALIASING_ARM: VkImageLayout = 1000460000;
pub const VkImageLayout_VK_IMAGE_LAYOUT_VIDEO_ENCODE_QUANTIZATION_MAP_KHR: VkImageLayout =
    1000553000;
pub const VkImageLayout_VK_IMAGE_LAYOUT_ZERO_INITIALIZED_EXT: VkImageLayout = 1000620000;
pub const VkImageLayout_VK_IMAGE_LAYOUT_DEPTH_READ_ONLY_STENCIL_ATTACHMENT_OPTIMAL_KHR:
    VkImageLayout = 1000117000;
pub const VkImageLayout_VK_IMAGE_LAYOUT_DEPTH_ATTACHMENT_STENCIL_READ_ONLY_OPTIMAL_KHR:
    VkImageLayout = 1000117001;
pub const VkImageLayout_VK_IMAGE_LAYOUT_SHADING_RATE_OPTIMAL_NV: VkImageLayout = 1000164003;
pub const VkImageLayout_VK_IMAGE_LAYOUT_RENDERING_LOCAL_READ_KHR: VkImageLayout = 1000232000;
pub const VkImageLayout_VK_IMAGE_LAYOUT_DEPTH_ATTACHMENT_OPTIMAL_KHR: VkImageLayout = 1000241000;
pub const VkImageLayout_VK_IMAGE_LAYOUT_DEPTH_READ_ONLY_OPTIMAL_KHR: VkImageLayout = 1000241001;
pub const VkImageLayout_VK_IMAGE_LAYOUT_STENCIL_ATTACHMENT_OPTIMAL_KHR: VkImageLayout = 1000241002;
pub const VkImageLayout_VK_IMAGE_LAYOUT_STENCIL_READ_ONLY_OPTIMAL_KHR: VkImageLayout = 1000241003;
pub const VkImageLayout_VK_IMAGE_LAYOUT_READ_ONLY_OPTIMAL_KHR: VkImageLayout = 1000314000;
pub const VkImageLayout_VK_IMAGE_LAYOUT_ATTACHMENT_OPTIMAL_KHR: VkImageLayout = 1000314001;
pub const VkImageLayout_VK_IMAGE_LAYOUT_MAX_ENUM: VkImageLayout = 2147483647;
pub type VkImageLayout = ::std::os::raw::c_uint;
pub const VkFormat_VK_FORMAT_UNDEFINED: VkFormat = 0;
pub const VkFormat_VK_FORMAT_R4G4_UNORM_PACK8: VkFormat = 1;
pub const VkFormat_VK_FORMAT_R4G4B4A4_UNORM_PACK16: VkFormat = 2;
pub const VkFormat_VK_FORMAT_B4G4R4A4_UNORM_PACK16: VkFormat = 3;
pub const VkFormat_VK_FORMAT_R5G6B5_UNORM_PACK16: VkFormat = 4;
pub const VkFormat_VK_FORMAT_B5G6R5_UNORM_PACK16: VkFormat = 5;
pub const VkFormat_VK_FORMAT_R5G5B5A1_UNORM_PACK16: VkFormat = 6;
pub const VkFormat_VK_FORMAT_B5G5R5A1_UNORM_PACK16: VkFormat = 7;
pub const VkFormat_VK_FORMAT_A1R5G5B5_UNORM_PACK16: VkFormat = 8;
pub const VkFormat_VK_FORMAT_R8_UNORM: VkFormat = 9;
pub const VkFormat_VK_FORMAT_R8_SNORM: VkFormat = 10;
pub const VkFormat_VK_FORMAT_R8_USCALED: VkFormat = 11;
pub const VkFormat_VK_FORMAT_R8_SSCALED: VkFormat = 12;
pub const VkFormat_VK_FORMAT_R8_UINT: VkFormat = 13;
pub const VkFormat_VK_FORMAT_R8_SINT: VkFormat = 14;
pub const VkFormat_VK_FORMAT_R8_SRGB: VkFormat = 15;
pub const VkFormat_VK_FORMAT_R8G8_UNORM: VkFormat = 16;
pub const VkFormat_VK_FORMAT_R8G8_SNORM: VkFormat = 17;
pub const VkFormat_VK_FORMAT_R8G8_USCALED: VkFormat = 18;
pub const VkFormat_VK_FORMAT_R8G8_SSCALED: VkFormat = 19;
pub const VkFormat_VK_FORMAT_R8G8_UINT: VkFormat = 20;
pub const VkFormat_VK_FORMAT_R8G8_SINT: VkFormat = 21;
pub const VkFormat_VK_FORMAT_R8G8_SRGB: VkFormat = 22;
pub const VkFormat_VK_FORMAT_R8G8B8_UNORM: VkFormat = 23;
pub const VkFormat_VK_FORMAT_R8G8B8_SNORM: VkFormat = 24;
pub const VkFormat_VK_FORMAT_R8G8B8_USCALED: VkFormat = 25;
pub const VkFormat_VK_FORMAT_R8G8B8_SSCALED: VkFormat = 26;
pub const VkFormat_VK_FORMAT_R8G8B8_UINT: VkFormat = 27;
pub const VkFormat_VK_FORMAT_R8G8B8_SINT: VkFormat = 28;
pub const VkFormat_VK_FORMAT_R8G8B8_SRGB: VkFormat = 29;
pub const VkFormat_VK_FORMAT_B8G8R8_UNORM: VkFormat = 30;
pub const VkFormat_VK_FORMAT_B8G8R8_SNORM: VkFormat = 31;
pub const VkFormat_VK_FORMAT_B8G8R8_USCALED: VkFormat = 32;
pub const VkFormat_VK_FORMAT_B8G8R8_SSCALED: VkFormat = 33;
pub const VkFormat_VK_FORMAT_B8G8R8_UINT: VkFormat = 34;
pub const VkFormat_VK_FORMAT_B8G8R8_SINT: VkFormat = 35;
pub const VkFormat_VK_FORMAT_B8G8R8_SRGB: VkFormat = 36;
pub const VkFormat_VK_FORMAT_R8G8B8A8_UNORM: VkFormat = 37;
pub const VkFormat_VK_FORMAT_R8G8B8A8_SNORM: VkFormat = 38;
pub const VkFormat_VK_FORMAT_R8G8B8A8_USCALED: VkFormat = 39;
pub const VkFormat_VK_FORMAT_R8G8B8A8_SSCALED: VkFormat = 40;
pub const VkFormat_VK_FORMAT_R8G8B8A8_UINT: VkFormat = 41;
pub const VkFormat_VK_FORMAT_R8G8B8A8_SINT: VkFormat = 42;
pub const VkFormat_VK_FORMAT_R8G8B8A8_SRGB: VkFormat = 43;
pub const VkFormat_VK_FORMAT_B8G8R8A8_UNORM: VkFormat = 44;
pub const VkFormat_VK_FORMAT_B8G8R8A8_SNORM: VkFormat = 45;
pub const VkFormat_VK_FORMAT_B8G8R8A8_USCALED: VkFormat = 46;
pub const VkFormat_VK_FORMAT_B8G8R8A8_SSCALED: VkFormat = 47;
pub const VkFormat_VK_FORMAT_B8G8R8A8_UINT: VkFormat = 48;
pub const VkFormat_VK_FORMAT_B8G8R8A8_SINT: VkFormat = 49;
pub const VkFormat_VK_FORMAT_B8G8R8A8_SRGB: VkFormat = 50;
pub const VkFormat_VK_FORMAT_A8B8G8R8_UNORM_PACK32: VkFormat = 51;
pub const VkFormat_VK_FORMAT_A8B8G8R8_SNORM_PACK32: VkFormat = 52;
pub const VkFormat_VK_FORMAT_A8B8G8R8_USCALED_PACK32: VkFormat = 53;
pub const VkFormat_VK_FORMAT_A8B8G8R8_SSCALED_PACK32: VkFormat = 54;
pub const VkFormat_VK_FORMAT_A8B8G8R8_UINT_PACK32: VkFormat = 55;
pub const VkFormat_VK_FORMAT_A8B8G8R8_SINT_PACK32: VkFormat = 56;
pub const VkFormat_VK_FORMAT_A8B8G8R8_SRGB_PACK32: VkFormat = 57;
pub const VkFormat_VK_FORMAT_A2R10G10B10_UNORM_PACK32: VkFormat = 58;
pub const VkFormat_VK_FORMAT_A2R10G10B10_SNORM_PACK32: VkFormat = 59;
pub const VkFormat_VK_FORMAT_A2R10G10B10_USCALED_PACK32: VkFormat = 60;
pub const VkFormat_VK_FORMAT_A2R10G10B10_SSCALED_PACK32: VkFormat = 61;
pub const VkFormat_VK_FORMAT_A2R10G10B10_UINT_PACK32: VkFormat = 62;
pub const VkFormat_VK_FORMAT_A2R10G10B10_SINT_PACK32: VkFormat = 63;
pub const VkFormat_VK_FORMAT_A2B10G10R10_UNORM_PACK32: VkFormat = 64;
pub const VkFormat_VK_FORMAT_A2B10G10R10_SNORM_PACK32: VkFormat = 65;
pub const VkFormat_VK_FORMAT_A2B10G10R10_USCALED_PACK32: VkFormat = 66;
pub const VkFormat_VK_FORMAT_A2B10G10R10_SSCALED_PACK32: VkFormat = 67;
pub const VkFormat_VK_FORMAT_A2B10G10R10_UINT_PACK32: VkFormat = 68;
pub const VkFormat_VK_FORMAT_A2B10G10R10_SINT_PACK32: VkFormat = 69;
pub const VkFormat_VK_FORMAT_R16_UNORM: VkFormat = 70;
pub const VkFormat_VK_FORMAT_R16_SNORM: VkFormat = 71;
pub const VkFormat_VK_FORMAT_R16_USCALED: VkFormat = 72;
pub const VkFormat_VK_FORMAT_R16_SSCALED: VkFormat = 73;
pub const VkFormat_VK_FORMAT_R16_UINT: VkFormat = 74;
pub const VkFormat_VK_FORMAT_R16_SINT: VkFormat = 75;
pub const VkFormat_VK_FORMAT_R16_SFLOAT: VkFormat = 76;
pub const VkFormat_VK_FORMAT_R16G16_UNORM: VkFormat = 77;
pub const VkFormat_VK_FORMAT_R16G16_SNORM: VkFormat = 78;
pub const VkFormat_VK_FORMAT_R16G16_USCALED: VkFormat = 79;
pub const VkFormat_VK_FORMAT_R16G16_SSCALED: VkFormat = 80;
pub const VkFormat_VK_FORMAT_R16G16_UINT: VkFormat = 81;
pub const VkFormat_VK_FORMAT_R16G16_SINT: VkFormat = 82;
pub const VkFormat_VK_FORMAT_R16G16_SFLOAT: VkFormat = 83;
pub const VkFormat_VK_FORMAT_R16G16B16_UNORM: VkFormat = 84;
pub const VkFormat_VK_FORMAT_R16G16B16_SNORM: VkFormat = 85;
pub const VkFormat_VK_FORMAT_R16G16B16_USCALED: VkFormat = 86;
pub const VkFormat_VK_FORMAT_R16G16B16_SSCALED: VkFormat = 87;
pub const VkFormat_VK_FORMAT_R16G16B16_UINT: VkFormat = 88;
pub const VkFormat_VK_FORMAT_R16G16B16_SINT: VkFormat = 89;
pub const VkFormat_VK_FORMAT_R16G16B16_SFLOAT: VkFormat = 90;
pub const VkFormat_VK_FORMAT_R16G16B16A16_UNORM: VkFormat = 91;
pub const VkFormat_VK_FORMAT_R16G16B16A16_SNORM: VkFormat = 92;
pub const VkFormat_VK_FORMAT_R16G16B16A16_USCALED: VkFormat = 93;
pub const VkFormat_VK_FORMAT_R16G16B16A16_SSCALED: VkFormat = 94;
pub const VkFormat_VK_FORMAT_R16G16B16A16_UINT: VkFormat = 95;
pub const VkFormat_VK_FORMAT_R16G16B16A16_SINT: VkFormat = 96;
pub const VkFormat_VK_FORMAT_R16G16B16A16_SFLOAT: VkFormat = 97;
pub const VkFormat_VK_FORMAT_R32_UINT: VkFormat = 98;
pub const VkFormat_VK_FORMAT_R32_SINT: VkFormat = 99;
pub const VkFormat_VK_FORMAT_R32_SFLOAT: VkFormat = 100;
pub const VkFormat_VK_FORMAT_R32G32_UINT: VkFormat = 101;
pub const VkFormat_VK_FORMAT_R32G32_SINT: VkFormat = 102;
pub const VkFormat_VK_FORMAT_R32G32_SFLOAT: VkFormat = 103;
pub const VkFormat_VK_FORMAT_R32G32B32_UINT: VkFormat = 104;
pub const VkFormat_VK_FORMAT_R32G32B32_SINT: VkFormat = 105;
pub const VkFormat_VK_FORMAT_R32G32B32_SFLOAT: VkFormat = 106;
pub const VkFormat_VK_FORMAT_R32G32B32A32_UINT: VkFormat = 107;
pub const VkFormat_VK_FORMAT_R32G32B32A32_SINT: VkFormat = 108;
pub const VkFormat_VK_FORMAT_R32G32B32A32_SFLOAT: VkFormat = 109;
pub const VkFormat_VK_FORMAT_R64_UINT: VkFormat = 110;
pub const VkFormat_VK_FORMAT_R64_SINT: VkFormat = 111;
pub const VkFormat_VK_FORMAT_R64_SFLOAT: VkFormat = 112;
pub const VkFormat_VK_FORMAT_R64G64_UINT: VkFormat = 113;
pub const VkFormat_VK_FORMAT_R64G64_SINT: VkFormat = 114;
pub const VkFormat_VK_FORMAT_R64G64_SFLOAT: VkFormat = 115;
pub const VkFormat_VK_FORMAT_R64G64B64_UINT: VkFormat = 116;
pub const VkFormat_VK_FORMAT_R64G64B64_SINT: VkFormat = 117;
pub const VkFormat_VK_FORMAT_R64G64B64_SFLOAT: VkFormat = 118;
pub const VkFormat_VK_FORMAT_R64G64B64A64_UINT: VkFormat = 119;
pub const VkFormat_VK_FORMAT_R64G64B64A64_SINT: VkFormat = 120;
pub const VkFormat_VK_FORMAT_R64G64B64A64_SFLOAT: VkFormat = 121;
pub const VkFormat_VK_FORMAT_B10G11R11_UFLOAT_PACK32: VkFormat = 122;
pub const VkFormat_VK_FORMAT_E5B9G9R9_UFLOAT_PACK32: VkFormat = 123;
pub const VkFormat_VK_FORMAT_D16_UNORM: VkFormat = 124;
pub const VkFormat_VK_FORMAT_X8_D24_UNORM_PACK32: VkFormat = 125;
pub const VkFormat_VK_FORMAT_D32_SFLOAT: VkFormat = 126;
pub const VkFormat_VK_FORMAT_S8_UINT: VkFormat = 127;
pub const VkFormat_VK_FORMAT_D16_UNORM_S8_UINT: VkFormat = 128;
pub const VkFormat_VK_FORMAT_D24_UNORM_S8_UINT: VkFormat = 129;
pub const VkFormat_VK_FORMAT_D32_SFLOAT_S8_UINT: VkFormat = 130;
pub const VkFormat_VK_FORMAT_BC1_RGB_UNORM_BLOCK: VkFormat = 131;
pub const VkFormat_VK_FORMAT_BC1_RGB_SRGB_BLOCK: VkFormat = 132;
pub const VkFormat_VK_FORMAT_BC1_RGBA_UNORM_BLOCK: VkFormat = 133;
pub const VkFormat_VK_FORMAT_BC1_RGBA_SRGB_BLOCK: VkFormat = 134;
pub const VkFormat_VK_FORMAT_BC2_UNORM_BLOCK: VkFormat = 135;
pub const VkFormat_VK_FORMAT_BC2_SRGB_BLOCK: VkFormat = 136;
pub const VkFormat_VK_FORMAT_BC3_UNORM_BLOCK: VkFormat = 137;
pub const VkFormat_VK_FORMAT_BC3_SRGB_BLOCK: VkFormat = 138;
pub const VkFormat_VK_FORMAT_BC4_UNORM_BLOCK: VkFormat = 139;
pub const VkFormat_VK_FORMAT_BC4_SNORM_BLOCK: VkFormat = 140;
pub const VkFormat_VK_FORMAT_BC5_UNORM_BLOCK: VkFormat = 141;
pub const VkFormat_VK_FORMAT_BC5_SNORM_BLOCK: VkFormat = 142;
pub const VkFormat_VK_FORMAT_BC6H_UFLOAT_BLOCK: VkFormat = 143;
pub const VkFormat_VK_FORMAT_BC6H_SFLOAT_BLOCK: VkFormat = 144;
pub const VkFormat_VK_FORMAT_BC7_UNORM_BLOCK: VkFormat = 145;
pub const VkFormat_VK_FORMAT_BC7_SRGB_BLOCK: VkFormat = 146;
pub const VkFormat_VK_FORMAT_ETC2_R8G8B8_UNORM_BLOCK: VkFormat = 147;
pub const VkFormat_VK_FORMAT_ETC2_R8G8B8_SRGB_BLOCK: VkFormat = 148;
pub const VkFormat_VK_FORMAT_ETC2_R8G8B8A1_UNORM_BLOCK: VkFormat = 149;
pub const VkFormat_VK_FORMAT_ETC2_R8G8B8A1_SRGB_BLOCK: VkFormat = 150;
pub const VkFormat_VK_FORMAT_ETC2_R8G8B8A8_UNORM_BLOCK: VkFormat = 151;
pub const VkFormat_VK_FORMAT_ETC2_R8G8B8A8_SRGB_BLOCK: VkFormat = 152;
pub const VkFormat_VK_FORMAT_EAC_R11_UNORM_BLOCK: VkFormat = 153;
pub const VkFormat_VK_FORMAT_EAC_R11_SNORM_BLOCK: VkFormat = 154;
pub const VkFormat_VK_FORMAT_EAC_R11G11_UNORM_BLOCK: VkFormat = 155;
pub const VkFormat_VK_FORMAT_EAC_R11G11_SNORM_BLOCK: VkFormat = 156;
pub const VkFormat_VK_FORMAT_ASTC_4x4_UNORM_BLOCK: VkFormat = 157;
pub const VkFormat_VK_FORMAT_ASTC_4x4_SRGB_BLOCK: VkFormat = 158;
pub const VkFormat_VK_FORMAT_ASTC_5x4_UNORM_BLOCK: VkFormat = 159;
pub const VkFormat_VK_FORMAT_ASTC_5x4_SRGB_BLOCK: VkFormat = 160;
pub const VkFormat_VK_FORMAT_ASTC_5x5_UNORM_BLOCK: VkFormat = 161;
pub const VkFormat_VK_FORMAT_ASTC_5x5_SRGB_BLOCK: VkFormat = 162;
pub const VkFormat_VK_FORMAT_ASTC_6x5_UNORM_BLOCK: VkFormat = 163;
pub const VkFormat_VK_FORMAT_ASTC_6x5_SRGB_BLOCK: VkFormat = 164;
pub const VkFormat_VK_FORMAT_ASTC_6x6_UNORM_BLOCK: VkFormat = 165;
pub const VkFormat_VK_FORMAT_ASTC_6x6_SRGB_BLOCK: VkFormat = 166;
pub const VkFormat_VK_FORMAT_ASTC_8x5_UNORM_BLOCK: VkFormat = 167;
pub const VkFormat_VK_FORMAT_ASTC_8x5_SRGB_BLOCK: VkFormat = 168;
pub const VkFormat_VK_FORMAT_ASTC_8x6_UNORM_BLOCK: VkFormat = 169;
pub const VkFormat_VK_FORMAT_ASTC_8x6_SRGB_BLOCK: VkFormat = 170;
pub const VkFormat_VK_FORMAT_ASTC_8x8_UNORM_BLOCK: VkFormat = 171;
pub const VkFormat_VK_FORMAT_ASTC_8x8_SRGB_BLOCK: VkFormat = 172;
pub const VkFormat_VK_FORMAT_ASTC_10x5_UNORM_BLOCK: VkFormat = 173;
pub const VkFormat_VK_FORMAT_ASTC_10x5_SRGB_BLOCK: VkFormat = 174;
pub const VkFormat_VK_FORMAT_ASTC_10x6_UNORM_BLOCK: VkFormat = 175;
pub const VkFormat_VK_FORMAT_ASTC_10x6_SRGB_BLOCK: VkFormat = 176;
pub const VkFormat_VK_FORMAT_ASTC_10x8_UNORM_BLOCK: VkFormat = 177;
pub const VkFormat_VK_FORMAT_ASTC_10x8_SRGB_BLOCK: VkFormat = 178;
pub const VkFormat_VK_FORMAT_ASTC_10x10_UNORM_BLOCK: VkFormat = 179;
pub const VkFormat_VK_FORMAT_ASTC_10x10_SRGB_BLOCK: VkFormat = 180;
pub const VkFormat_VK_FORMAT_ASTC_12x10_UNORM_BLOCK: VkFormat = 181;
pub const VkFormat_VK_FORMAT_ASTC_12x10_SRGB_BLOCK: VkFormat = 182;
pub const VkFormat_VK_FORMAT_ASTC_12x12_UNORM_BLOCK: VkFormat = 183;
pub const VkFormat_VK_FORMAT_ASTC_12x12_SRGB_BLOCK: VkFormat = 184;
pub const VkFormat_VK_FORMAT_G8B8G8R8_422_UNORM: VkFormat = 1000156000;
pub const VkFormat_VK_FORMAT_B8G8R8G8_422_UNORM: VkFormat = 1000156001;
pub const VkFormat_VK_FORMAT_G8_B8_R8_3PLANE_420_UNORM: VkFormat = 1000156002;
pub const VkFormat_VK_FORMAT_G8_B8R8_2PLANE_420_UNORM: VkFormat = 1000156003;
pub const VkFormat_VK_FORMAT_G8_B8_R8_3PLANE_422_UNORM: VkFormat = 1000156004;
pub const VkFormat_VK_FORMAT_G8_B8R8_2PLANE_422_UNORM: VkFormat = 1000156005;
pub const VkFormat_VK_FORMAT_G8_B8_R8_3PLANE_444_UNORM: VkFormat = 1000156006;
pub const VkFormat_VK_FORMAT_R10X6_UNORM_PACK16: VkFormat = 1000156007;
pub const VkFormat_VK_FORMAT_R10X6G10X6_UNORM_2PACK16: VkFormat = 1000156008;
pub const VkFormat_VK_FORMAT_R10X6G10X6B10X6A10X6_UNORM_4PACK16: VkFormat = 1000156009;
pub const VkFormat_VK_FORMAT_G10X6B10X6G10X6R10X6_422_UNORM_4PACK16: VkFormat = 1000156010;
pub const VkFormat_VK_FORMAT_B10X6G10X6R10X6G10X6_422_UNORM_4PACK16: VkFormat = 1000156011;
pub const VkFormat_VK_FORMAT_G10X6_B10X6_R10X6_3PLANE_420_UNORM_3PACK16: VkFormat = 1000156012;
pub const VkFormat_VK_FORMAT_G10X6_B10X6R10X6_2PLANE_420_UNORM_3PACK16: VkFormat = 1000156013;
pub const VkFormat_VK_FORMAT_G10X6_B10X6_R10X6_3PLANE_422_UNORM_3PACK16: VkFormat = 1000156014;
pub const VkFormat_VK_FORMAT_G10X6_B10X6R10X6_2PLANE_422_UNORM_3PACK16: VkFormat = 1000156015;
pub const VkFormat_VK_FORMAT_G10X6_B10X6_R10X6_3PLANE_444_UNORM_3PACK16: VkFormat = 1000156016;
pub const VkFormat_VK_FORMAT_R12X4_UNORM_PACK16: VkFormat = 1000156017;
pub const VkFormat_VK_FORMAT_R12X4G12X4_UNORM_2PACK16: VkFormat = 1000156018;
pub const VkFormat_VK_FORMAT_R12X4G12X4B12X4A12X4_UNORM_4PACK16: VkFormat = 1000156019;
pub const VkFormat_VK_FORMAT_G12X4B12X4G12X4R12X4_422_UNORM_4PACK16: VkFormat = 1000156020;
pub const VkFormat_VK_FORMAT_B12X4G12X4R12X4G12X4_422_UNORM_4PACK16: VkFormat = 1000156021;
pub const VkFormat_VK_FORMAT_G12X4_B12X4_R12X4_3PLANE_420_UNORM_3PACK16: VkFormat = 1000156022;
pub const VkFormat_VK_FORMAT_G12X4_B12X4R12X4_2PLANE_420_UNORM_3PACK16: VkFormat = 1000156023;
pub const VkFormat_VK_FORMAT_G12X4_B12X4_R12X4_3PLANE_422_UNORM_3PACK16: VkFormat = 1000156024;
pub const VkFormat_VK_FORMAT_G12X4_B12X4R12X4_2PLANE_422_UNORM_3PACK16: VkFormat = 1000156025;
pub const VkFormat_VK_FORMAT_G12X4_B12X4_R12X4_3PLANE_444_UNORM_3PACK16: VkFormat = 1000156026;
pub const VkFormat_VK_FORMAT_G16B16G16R16_422_UNORM: VkFormat = 1000156027;
pub const VkFormat_VK_FORMAT_B16G16R16G16_422_UNORM: VkFormat = 1000156028;
pub const VkFormat_VK_FORMAT_G16_B16_R16_3PLANE_420_UNORM: VkFormat = 1000156029;
pub const VkFormat_VK_FORMAT_G16_B16R16_2PLANE_420_UNORM: VkFormat = 1000156030;
pub const VkFormat_VK_FORMAT_G16_B16_R16_3PLANE_422_UNORM: VkFormat = 1000156031;
pub const VkFormat_VK_FORMAT_G16_B16R16_2PLANE_422_UNORM: VkFormat = 1000156032;
pub const VkFormat_VK_FORMAT_G16_B16_R16_3PLANE_444_UNORM: VkFormat = 1000156033;
pub const VkFormat_VK_FORMAT_G8_B8R8_2PLANE_444_UNORM: VkFormat = 1000330000;
pub const VkFormat_VK_FORMAT_G10X6_B10X6R10X6_2PLANE_444_UNORM_3PACK16: VkFormat = 1000330001;
pub const VkFormat_VK_FORMAT_G12X4_B12X4R12X4_2PLANE_444_UNORM_3PACK16: VkFormat = 1000330002;
pub const VkFormat_VK_FORMAT_G16_B16R16_2PLANE_444_UNORM: VkFormat = 1000330003;
pub const VkFormat_VK_FORMAT_A4R4G4B4_UNORM_PACK16: VkFormat = 1000340000;
pub const VkFormat_VK_FORMAT_A4B4G4R4_UNORM_PACK16: VkFormat = 1000340001;
pub const VkFormat_VK_FORMAT_ASTC_4x4_SFLOAT_BLOCK: VkFormat = 1000066000;
pub const VkFormat_VK_FORMAT_ASTC_5x4_SFLOAT_BLOCK: VkFormat = 1000066001;
pub const VkFormat_VK_FORMAT_ASTC_5x5_SFLOAT_BLOCK: VkFormat = 1000066002;
pub const VkFormat_VK_FORMAT_ASTC_6x5_SFLOAT_BLOCK: VkFormat = 1000066003;
pub const VkFormat_VK_FORMAT_ASTC_6x6_SFLOAT_BLOCK: VkFormat = 1000066004;
pub const VkFormat_VK_FORMAT_ASTC_8x5_SFLOAT_BLOCK: VkFormat = 1000066005;
pub const VkFormat_VK_FORMAT_ASTC_8x6_SFLOAT_BLOCK: VkFormat = 1000066006;
pub const VkFormat_VK_FORMAT_ASTC_8x8_SFLOAT_BLOCK: VkFormat = 1000066007;
pub const VkFormat_VK_FORMAT_ASTC_10x5_SFLOAT_BLOCK: VkFormat = 1000066008;
pub const VkFormat_VK_FORMAT_ASTC_10x6_SFLOAT_BLOCK: VkFormat = 1000066009;
pub const VkFormat_VK_FORMAT_ASTC_10x8_SFLOAT_BLOCK: VkFormat = 1000066010;
pub const VkFormat_VK_FORMAT_ASTC_10x10_SFLOAT_BLOCK: VkFormat = 1000066011;
pub const VkFormat_VK_FORMAT_ASTC_12x10_SFLOAT_BLOCK: VkFormat = 1000066012;
pub const VkFormat_VK_FORMAT_ASTC_12x12_SFLOAT_BLOCK: VkFormat = 1000066013;
pub const VkFormat_VK_FORMAT_A1B5G5R5_UNORM_PACK16: VkFormat = 1000470000;
pub const VkFormat_VK_FORMAT_A8_UNORM: VkFormat = 1000470001;
pub const VkFormat_VK_FORMAT_PVRTC1_2BPP_UNORM_BLOCK_IMG: VkFormat = 1000054000;
pub const VkFormat_VK_FORMAT_PVRTC1_4BPP_UNORM_BLOCK_IMG: VkFormat = 1000054001;
pub const VkFormat_VK_FORMAT_PVRTC2_2BPP_UNORM_BLOCK_IMG: VkFormat = 1000054002;
pub const VkFormat_VK_FORMAT_PVRTC2_4BPP_UNORM_BLOCK_IMG: VkFormat = 1000054003;
pub const VkFormat_VK_FORMAT_PVRTC1_2BPP_SRGB_BLOCK_IMG: VkFormat = 1000054004;
pub const VkFormat_VK_FORMAT_PVRTC1_4BPP_SRGB_BLOCK_IMG: VkFormat = 1000054005;
pub const VkFormat_VK_FORMAT_PVRTC2_2BPP_SRGB_BLOCK_IMG: VkFormat = 1000054006;
pub const VkFormat_VK_FORMAT_PVRTC2_4BPP_SRGB_BLOCK_IMG: VkFormat = 1000054007;
pub const VkFormat_VK_FORMAT_ASTC_3x3x3_UNORM_BLOCK_EXT: VkFormat = 1000288000;
pub const VkFormat_VK_FORMAT_ASTC_3x3x3_SRGB_BLOCK_EXT: VkFormat = 1000288001;
pub const VkFormat_VK_FORMAT_ASTC_3x3x3_SFLOAT_BLOCK_EXT: VkFormat = 1000288002;
pub const VkFormat_VK_FORMAT_ASTC_4x3x3_UNORM_BLOCK_EXT: VkFormat = 1000288003;
pub const VkFormat_VK_FORMAT_ASTC_4x3x3_SRGB_BLOCK_EXT: VkFormat = 1000288004;
pub const VkFormat_VK_FORMAT_ASTC_4x3x3_SFLOAT_BLOCK_EXT: VkFormat = 1000288005;
pub const VkFormat_VK_FORMAT_ASTC_4x4x3_UNORM_BLOCK_EXT: VkFormat = 1000288006;
pub const VkFormat_VK_FORMAT_ASTC_4x4x3_SRGB_BLOCK_EXT: VkFormat = 1000288007;
pub const VkFormat_VK_FORMAT_ASTC_4x4x3_SFLOAT_BLOCK_EXT: VkFormat = 1000288008;
pub const VkFormat_VK_FORMAT_ASTC_4x4x4_UNORM_BLOCK_EXT: VkFormat = 1000288009;
pub const VkFormat_VK_FORMAT_ASTC_4x4x4_SRGB_BLOCK_EXT: VkFormat = 1000288010;
pub const VkFormat_VK_FORMAT_ASTC_4x4x4_SFLOAT_BLOCK_EXT: VkFormat = 1000288011;
pub const VkFormat_VK_FORMAT_ASTC_5x4x4_UNORM_BLOCK_EXT: VkFormat = 1000288012;
pub const VkFormat_VK_FORMAT_ASTC_5x4x4_SRGB_BLOCK_EXT: VkFormat = 1000288013;
pub const VkFormat_VK_FORMAT_ASTC_5x4x4_SFLOAT_BLOCK_EXT: VkFormat = 1000288014;
pub const VkFormat_VK_FORMAT_ASTC_5x5x4_UNORM_BLOCK_EXT: VkFormat = 1000288015;
pub const VkFormat_VK_FORMAT_ASTC_5x5x4_SRGB_BLOCK_EXT: VkFormat = 1000288016;
pub const VkFormat_VK_FORMAT_ASTC_5x5x4_SFLOAT_BLOCK_EXT: VkFormat = 1000288017;
pub const VkFormat_VK_FORMAT_ASTC_5x5x5_UNORM_BLOCK_EXT: VkFormat = 1000288018;
pub const VkFormat_VK_FORMAT_ASTC_5x5x5_SRGB_BLOCK_EXT: VkFormat = 1000288019;
pub const VkFormat_VK_FORMAT_ASTC_5x5x5_SFLOAT_BLOCK_EXT: VkFormat = 1000288020;
pub const VkFormat_VK_FORMAT_ASTC_6x5x5_UNORM_BLOCK_EXT: VkFormat = 1000288021;
pub const VkFormat_VK_FORMAT_ASTC_6x5x5_SRGB_BLOCK_EXT: VkFormat = 1000288022;
pub const VkFormat_VK_FORMAT_ASTC_6x5x5_SFLOAT_BLOCK_EXT: VkFormat = 1000288023;
pub const VkFormat_VK_FORMAT_ASTC_6x6x5_UNORM_BLOCK_EXT: VkFormat = 1000288024;
pub const VkFormat_VK_FORMAT_ASTC_6x6x5_SRGB_BLOCK_EXT: VkFormat = 1000288025;
pub const VkFormat_VK_FORMAT_ASTC_6x6x5_SFLOAT_BLOCK_EXT: VkFormat = 1000288026;
pub const VkFormat_VK_FORMAT_ASTC_6x6x6_UNORM_BLOCK_EXT: VkFormat = 1000288027;
pub const VkFormat_VK_FORMAT_ASTC_6x6x6_SRGB_BLOCK_EXT: VkFormat = 1000288028;
pub const VkFormat_VK_FORMAT_ASTC_6x6x6_SFLOAT_BLOCK_EXT: VkFormat = 1000288029;
pub const VkFormat_VK_FORMAT_R8_BOOL_ARM: VkFormat = 1000460000;
pub const VkFormat_VK_FORMAT_R16G16_SFIXED5_NV: VkFormat = 1000464000;
pub const VkFormat_VK_FORMAT_R10X6_UINT_PACK16_ARM: VkFormat = 1000609000;
pub const VkFormat_VK_FORMAT_R10X6G10X6_UINT_2PACK16_ARM: VkFormat = 1000609001;
pub const VkFormat_VK_FORMAT_R10X6G10X6B10X6A10X6_UINT_4PACK16_ARM: VkFormat = 1000609002;
pub const VkFormat_VK_FORMAT_R12X4_UINT_PACK16_ARM: VkFormat = 1000609003;
pub const VkFormat_VK_FORMAT_R12X4G12X4_UINT_2PACK16_ARM: VkFormat = 1000609004;
pub const VkFormat_VK_FORMAT_R12X4G12X4B12X4A12X4_UINT_4PACK16_ARM: VkFormat = 1000609005;
pub const VkFormat_VK_FORMAT_R14X2_UINT_PACK16_ARM: VkFormat = 1000609006;
pub const VkFormat_VK_FORMAT_R14X2G14X2_UINT_2PACK16_ARM: VkFormat = 1000609007;
pub const VkFormat_VK_FORMAT_R14X2G14X2B14X2A14X2_UINT_4PACK16_ARM: VkFormat = 1000609008;
pub const VkFormat_VK_FORMAT_R14X2_UNORM_PACK16_ARM: VkFormat = 1000609009;
pub const VkFormat_VK_FORMAT_R14X2G14X2_UNORM_2PACK16_ARM: VkFormat = 1000609010;
pub const VkFormat_VK_FORMAT_R14X2G14X2B14X2A14X2_UNORM_4PACK16_ARM: VkFormat = 1000609011;
pub const VkFormat_VK_FORMAT_G14X2_B14X2R14X2_2PLANE_420_UNORM_3PACK16_ARM: VkFormat = 1000609012;
pub const VkFormat_VK_FORMAT_G14X2_B14X2R14X2_2PLANE_422_UNORM_3PACK16_ARM: VkFormat = 1000609013;
pub const VkFormat_VK_FORMAT_ASTC_4x4_SFLOAT_BLOCK_EXT: VkFormat = 1000066000;
pub const VkFormat_VK_FORMAT_ASTC_5x4_SFLOAT_BLOCK_EXT: VkFormat = 1000066001;
pub const VkFormat_VK_FORMAT_ASTC_5x5_SFLOAT_BLOCK_EXT: VkFormat = 1000066002;
pub const VkFormat_VK_FORMAT_ASTC_6x5_SFLOAT_BLOCK_EXT: VkFormat = 1000066003;
pub const VkFormat_VK_FORMAT_ASTC_6x6_SFLOAT_BLOCK_EXT: VkFormat = 1000066004;
pub const VkFormat_VK_FORMAT_ASTC_8x5_SFLOAT_BLOCK_EXT: VkFormat = 1000066005;
pub const VkFormat_VK_FORMAT_ASTC_8x6_SFLOAT_BLOCK_EXT: VkFormat = 1000066006;
pub const VkFormat_VK_FORMAT_ASTC_8x8_SFLOAT_BLOCK_EXT: VkFormat = 1000066007;
pub const VkFormat_VK_FORMAT_ASTC_10x5_SFLOAT_BLOCK_EXT: VkFormat = 1000066008;
pub const VkFormat_VK_FORMAT_ASTC_10x6_SFLOAT_BLOCK_EXT: VkFormat = 1000066009;
pub const VkFormat_VK_FORMAT_ASTC_10x8_SFLOAT_BLOCK_EXT: VkFormat = 1000066010;
pub const VkFormat_VK_FORMAT_ASTC_10x10_SFLOAT_BLOCK_EXT: VkFormat = 1000066011;
pub const VkFormat_VK_FORMAT_ASTC_12x10_SFLOAT_BLOCK_EXT: VkFormat = 1000066012;
pub const VkFormat_VK_FORMAT_ASTC_12x12_SFLOAT_BLOCK_EXT: VkFormat = 1000066013;
pub const VkFormat_VK_FORMAT_G8B8G8R8_422_UNORM_KHR: VkFormat = 1000156000;
pub const VkFormat_VK_FORMAT_B8G8R8G8_422_UNORM_KHR: VkFormat = 1000156001;
pub const VkFormat_VK_FORMAT_G8_B8_R8_3PLANE_420_UNORM_KHR: VkFormat = 1000156002;
pub const VkFormat_VK_FORMAT_G8_B8R8_2PLANE_420_UNORM_KHR: VkFormat = 1000156003;
pub const VkFormat_VK_FORMAT_G8_B8_R8_3PLANE_422_UNORM_KHR: VkFormat = 1000156004;
pub const VkFormat_VK_FORMAT_G8_B8R8_2PLANE_422_UNORM_KHR: VkFormat = 1000156005;
pub const VkFormat_VK_FORMAT_G8_B8_R8_3PLANE_444_UNORM_KHR: VkFormat = 1000156006;
pub const VkFormat_VK_FORMAT_R10X6_UNORM_PACK16_KHR: VkFormat = 1000156007;
pub const VkFormat_VK_FORMAT_R10X6G10X6_UNORM_2PACK16_KHR: VkFormat = 1000156008;
pub const VkFormat_VK_FORMAT_R10X6G10X6B10X6A10X6_UNORM_4PACK16_KHR: VkFormat = 1000156009;
pub const VkFormat_VK_FORMAT_G10X6B10X6G10X6R10X6_422_UNORM_4PACK16_KHR: VkFormat = 1000156010;
pub const VkFormat_VK_FORMAT_B10X6G10X6R10X6G10X6_422_UNORM_4PACK16_KHR: VkFormat = 1000156011;
pub const VkFormat_VK_FORMAT_G10X6_B10X6_R10X6_3PLANE_420_UNORM_3PACK16_KHR: VkFormat = 1000156012;
pub const VkFormat_VK_FORMAT_G10X6_B10X6R10X6_2PLANE_420_UNORM_3PACK16_KHR: VkFormat = 1000156013;
pub const VkFormat_VK_FORMAT_G10X6_B10X6_R10X6_3PLANE_422_UNORM_3PACK16_KHR: VkFormat = 1000156014;
pub const VkFormat_VK_FORMAT_G10X6_B10X6R10X6_2PLANE_422_UNORM_3PACK16_KHR: VkFormat = 1000156015;
pub const VkFormat_VK_FORMAT_G10X6_B10X6_R10X6_3PLANE_444_UNORM_3PACK16_KHR: VkFormat = 1000156016;
pub const VkFormat_VK_FORMAT_R12X4_UNORM_PACK16_KHR: VkFormat = 1000156017;
pub const VkFormat_VK_FORMAT_R12X4G12X4_UNORM_2PACK16_KHR: VkFormat = 1000156018;
pub const VkFormat_VK_FORMAT_R12X4G12X4B12X4A12X4_UNORM_4PACK16_KHR: VkFormat = 1000156019;
pub const VkFormat_VK_FORMAT_G12X4B12X4G12X4R12X4_422_UNORM_4PACK16_KHR: VkFormat = 1000156020;
pub const VkFormat_VK_FORMAT_B12X4G12X4R12X4G12X4_422_UNORM_4PACK16_KHR: VkFormat = 1000156021;
pub const VkFormat_VK_FORMAT_G12X4_B12X4_R12X4_3PLANE_420_UNORM_3PACK16_KHR: VkFormat = 1000156022;
pub const VkFormat_VK_FORMAT_G12X4_B12X4R12X4_2PLANE_420_UNORM_3PACK16_KHR: VkFormat = 1000156023;
pub const VkFormat_VK_FORMAT_G12X4_B12X4_R12X4_3PLANE_422_UNORM_3PACK16_KHR: VkFormat = 1000156024;
pub const VkFormat_VK_FORMAT_G12X4_B12X4R12X4_2PLANE_422_UNORM_3PACK16_KHR: VkFormat = 1000156025;
pub const VkFormat_VK_FORMAT_G12X4_B12X4_R12X4_3PLANE_444_UNORM_3PACK16_KHR: VkFormat = 1000156026;
pub const VkFormat_VK_FORMAT_G16B16G16R16_422_UNORM_KHR: VkFormat = 1000156027;
pub const VkFormat_VK_FORMAT_B16G16R16G16_422_UNORM_KHR: VkFormat = 1000156028;
pub const VkFormat_VK_FORMAT_G16_B16_R16_3PLANE_420_UNORM_KHR: VkFormat = 1000156029;
pub const VkFormat_VK_FORMAT_G16_B16R16_2PLANE_420_UNORM_KHR: VkFormat = 1000156030;
pub const VkFormat_VK_FORMAT_G16_B16_R16_3PLANE_422_UNORM_KHR: VkFormat = 1000156031;
pub const VkFormat_VK_FORMAT_G16_B16R16_2PLANE_422_UNORM_KHR: VkFormat = 1000156032;
pub const VkFormat_VK_FORMAT_G16_B16_R16_3PLANE_444_UNORM_KHR: VkFormat = 1000156033;
pub const VkFormat_VK_FORMAT_G8_B8R8_2PLANE_444_UNORM_EXT: VkFormat = 1000330000;
pub const VkFormat_VK_FORMAT_G10X6_B10X6R10X6_2PLANE_444_UNORM_3PACK16_EXT: VkFormat = 1000330001;
pub const VkFormat_VK_FORMAT_G12X4_B12X4R12X4_2PLANE_444_UNORM_3PACK16_EXT: VkFormat = 1000330002;
pub const VkFormat_VK_FORMAT_G16_B16R16_2PLANE_444_UNORM_EXT: VkFormat = 1000330003;
pub const VkFormat_VK_FORMAT_A4R4G4B4_UNORM_PACK16_EXT: VkFormat = 1000340000;
pub const VkFormat_VK_FORMAT_A4B4G4R4_UNORM_PACK16_EXT: VkFormat = 1000340001;
pub const VkFormat_VK_FORMAT_R16G16_S10_5_NV: VkFormat = 1000464000;
pub const VkFormat_VK_FORMAT_A1B5G5R5_UNORM_PACK16_KHR: VkFormat = 1000470000;
pub const VkFormat_VK_FORMAT_A8_UNORM_KHR: VkFormat = 1000470001;
pub const VkFormat_VK_FORMAT_MAX_ENUM: VkFormat = 2147483647;
pub type VkFormat = ::std::os::raw::c_uint;
pub const VkImageTiling_VK_IMAGE_TILING_OPTIMAL: VkImageTiling = 0;
pub const VkImageTiling_VK_IMAGE_TILING_LINEAR: VkImageTiling = 1;
pub const VkImageTiling_VK_IMAGE_TILING_DRM_FORMAT_MODIFIER_EXT: VkImageTiling = 1000158000;
pub const VkImageTiling_VK_IMAGE_TILING_MAX_ENUM: VkImageTiling = 2147483647;
pub type VkImageTiling = ::std::os::raw::c_uint;
pub const VkImageType_VK_IMAGE_TYPE_1D: VkImageType = 0;
pub const VkImageType_VK_IMAGE_TYPE_2D: VkImageType = 1;
pub const VkImageType_VK_IMAGE_TYPE_3D: VkImageType = 2;
pub const VkImageType_VK_IMAGE_TYPE_MAX_ENUM: VkImageType = 2147483647;
pub type VkImageType = ::std::os::raw::c_uint;
pub const VkCommandBufferLevel_VK_COMMAND_BUFFER_LEVEL_PRIMARY: VkCommandBufferLevel = 0;
pub const VkCommandBufferLevel_VK_COMMAND_BUFFER_LEVEL_SECONDARY: VkCommandBufferLevel = 1;
pub const VkCommandBufferLevel_VK_COMMAND_BUFFER_LEVEL_MAX_ENUM: VkCommandBufferLevel = 2147483647;
pub type VkCommandBufferLevel = ::std::os::raw::c_uint;
pub type VkAccessFlags = VkFlags;
pub type VkImageAspectFlags = VkFlags;
pub const VkSampleCountFlagBits_VK_SAMPLE_COUNT_1_BIT: VkSampleCountFlagBits = 1;
pub const VkSampleCountFlagBits_VK_SAMPLE_COUNT_2_BIT: VkSampleCountFlagBits = 2;
pub const VkSampleCountFlagBits_VK_SAMPLE_COUNT_4_BIT: VkSampleCountFlagBits = 4;
pub const VkSampleCountFlagBits_VK_SAMPLE_COUNT_8_BIT: VkSampleCountFlagBits = 8;
pub const VkSampleCountFlagBits_VK_SAMPLE_COUNT_16_BIT: VkSampleCountFlagBits = 16;
pub const VkSampleCountFlagBits_VK_SAMPLE_COUNT_32_BIT: VkSampleCountFlagBits = 32;
pub const VkSampleCountFlagBits_VK_SAMPLE_COUNT_64_BIT: VkSampleCountFlagBits = 64;
pub const VkSampleCountFlagBits_VK_SAMPLE_COUNT_FLAG_BITS_MAX_ENUM: VkSampleCountFlagBits =
    2147483647;
pub type VkSampleCountFlagBits = ::std::os::raw::c_uint;
pub type VkImageUsageFlags = VkFlags;
pub type VkMemoryPropertyFlags = VkFlags;
pub type VkPipelineStageFlags = VkFlags;
pub type VkBufferUsageFlags = VkFlags;
#[repr(C)]
#[derive(Default, Copy, Clone)]
pub struct VkExtent3D {
    pub width: u32,
    pub height: u32,
    pub depth: u32,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of VkExtent3D"][::std::mem::size_of::<VkExtent3D>() - 12usize];
    ["Alignment of VkExtent3D"][::std::mem::align_of::<VkExtent3D>() - 4usize];
    ["Offset of field: VkExtent3D::width"][::std::mem::offset_of!(VkExtent3D, width) - 0usize];
    ["Offset of field: VkExtent3D::height"][::std::mem::offset_of!(VkExtent3D, height) - 4usize];
    ["Offset of field: VkExtent3D::depth"][::std::mem::offset_of!(VkExtent3D, depth) - 8usize];
};
pub type PFN_vkVoidFunction = ::std::option::Option<unsafe extern "system" fn()>;
#[repr(C)]
#[derive(Default, Copy, Clone)]
pub struct VkImageSubresource {
    pub aspectMask: VkImageAspectFlags,
    pub mipLevel: u32,
    pub arrayLayer: u32,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of VkImageSubresource"][::std::mem::size_of::<VkImageSubresource>() - 12usize];
    ["Alignment of VkImageSubresource"][::std::mem::align_of::<VkImageSubresource>() - 4usize];
    ["Offset of field: VkImageSubresource::aspectMask"]
        [::std::mem::offset_of!(VkImageSubresource, aspectMask) - 0usize];
    ["Offset of field: VkImageSubresource::mipLevel"]
        [::std::mem::offset_of!(VkImageSubresource, mipLevel) - 4usize];
    ["Offset of field: VkImageSubresource::arrayLayer"]
        [::std::mem::offset_of!(VkImageSubresource, arrayLayer) - 8usize];
};
pub type PFN_vkGetInstanceProcAddr = ::std::option::Option<
    unsafe extern "system" fn(
        instance: VkInstance,
        pName: *const ::std::os::raw::c_char,
    ) -> PFN_vkVoidFunction,
>;
#[repr(C)]
#[derive(Copy, Clone)]
pub struct UnityVulkanInstance {
    pub pipelineCache: VkPipelineCache,
    pub instance: VkInstance,
    pub physicalDevice: VkPhysicalDevice,
    pub device: VkDevice,
    pub graphicsQueue: VkQueue,
    pub getInstanceProcAddr: PFN_vkGetInstanceProcAddr,
    pub queueFamilyIndex: ::std::os::raw::c_uint,
    pub reserved: [*mut ::std::os::raw::c_void; 8usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of UnityVulkanInstance"][::std::mem::size_of::<UnityVulkanInstance>() - 120usize];
    ["Alignment of UnityVulkanInstance"][::std::mem::align_of::<UnityVulkanInstance>() - 8usize];
    ["Offset of field: UnityVulkanInstance::pipelineCache"]
        [::std::mem::offset_of!(UnityVulkanInstance, pipelineCache) - 0usize];
    ["Offset of field: UnityVulkanInstance::instance"]
        [::std::mem::offset_of!(UnityVulkanInstance, instance) - 8usize];
    ["Offset of field: UnityVulkanInstance::physicalDevice"]
        [::std::mem::offset_of!(UnityVulkanInstance, physicalDevice) - 16usize];
    ["Offset of field: UnityVulkanInstance::device"]
        [::std::mem::offset_of!(UnityVulkanInstance, device) - 24usize];
    ["Offset of field: UnityVulkanInstance::graphicsQueue"]
        [::std::mem::offset_of!(UnityVulkanInstance, graphicsQueue) - 32usize];
    ["Offset of field: UnityVulkanInstance::getInstanceProcAddr"]
        [::std::mem::offset_of!(UnityVulkanInstance, getInstanceProcAddr) - 40usize];
    ["Offset of field: UnityVulkanInstance::queueFamilyIndex"]
        [::std::mem::offset_of!(UnityVulkanInstance, queueFamilyIndex) - 48usize];
    ["Offset of field: UnityVulkanInstance::reserved"]
        [::std::mem::offset_of!(UnityVulkanInstance, reserved) - 56usize];
};
impl Default for UnityVulkanInstance {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
#[repr(C)]
#[derive(Copy, Clone)]
pub struct UnityVulkanMemory {
    pub memory: VkDeviceMemory,
    pub offset: VkDeviceSize,
    pub size: VkDeviceSize,
    pub mapped: *mut ::std::os::raw::c_void,
    pub flags: VkMemoryPropertyFlags,
    pub memoryTypeIndex: ::std::os::raw::c_uint,
    pub reserved: [*mut ::std::os::raw::c_void; 4usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of UnityVulkanMemory"][::std::mem::size_of::<UnityVulkanMemory>() - 72usize];
    ["Alignment of UnityVulkanMemory"][::std::mem::align_of::<UnityVulkanMemory>() - 8usize];
    ["Offset of field: UnityVulkanMemory::memory"]
        [::std::mem::offset_of!(UnityVulkanMemory, memory) - 0usize];
    ["Offset of field: UnityVulkanMemory::offset"]
        [::std::mem::offset_of!(UnityVulkanMemory, offset) - 8usize];
    ["Offset of field: UnityVulkanMemory::size"]
        [::std::mem::offset_of!(UnityVulkanMemory, size) - 16usize];
    ["Offset of field: UnityVulkanMemory::mapped"]
        [::std::mem::offset_of!(UnityVulkanMemory, mapped) - 24usize];
    ["Offset of field: UnityVulkanMemory::flags"]
        [::std::mem::offset_of!(UnityVulkanMemory, flags) - 32usize];
    ["Offset of field: UnityVulkanMemory::memoryTypeIndex"]
        [::std::mem::offset_of!(UnityVulkanMemory, memoryTypeIndex) - 36usize];
    ["Offset of field: UnityVulkanMemory::reserved"]
        [::std::mem::offset_of!(UnityVulkanMemory, reserved) - 40usize];
};
impl Default for UnityVulkanMemory {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
pub const UnityVulkanResourceAccessMode_kUnityVulkanResourceAccess_ObserveOnly:
    UnityVulkanResourceAccessMode = 0;
pub const UnityVulkanResourceAccessMode_kUnityVulkanResourceAccess_PipelineBarrier:
    UnityVulkanResourceAccessMode = 1;
pub const UnityVulkanResourceAccessMode_kUnityVulkanResourceAccess_Recreate:
    UnityVulkanResourceAccessMode = 2;
pub type UnityVulkanResourceAccessMode = ::std::os::raw::c_uint;
#[repr(C)]
#[derive(Copy, Clone)]
pub struct UnityVulkanImage {
    pub memory: UnityVulkanMemory,
    pub image: VkImage,
    pub layout: VkImageLayout,
    pub aspect: VkImageAspectFlags,
    pub usage: VkImageUsageFlags,
    pub format: VkFormat,
    pub extent: VkExtent3D,
    pub tiling: VkImageTiling,
    pub type_: VkImageType,
    pub samples: VkSampleCountFlagBits,
    pub layers: ::std::os::raw::c_int,
    pub mipCount: ::std::os::raw::c_int,
    pub reserved: [*mut ::std::os::raw::c_void; 4usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of UnityVulkanImage"][::std::mem::size_of::<UnityVulkanImage>() - 160usize];
    ["Alignment of UnityVulkanImage"][::std::mem::align_of::<UnityVulkanImage>() - 8usize];
    ["Offset of field: UnityVulkanImage::memory"]
        [::std::mem::offset_of!(UnityVulkanImage, memory) - 0usize];
    ["Offset of field: UnityVulkanImage::image"]
        [::std::mem::offset_of!(UnityVulkanImage, image) - 72usize];
    ["Offset of field: UnityVulkanImage::layout"]
        [::std::mem::offset_of!(UnityVulkanImage, layout) - 80usize];
    ["Offset of field: UnityVulkanImage::aspect"]
        [::std::mem::offset_of!(UnityVulkanImage, aspect) - 84usize];
    ["Offset of field: UnityVulkanImage::usage"]
        [::std::mem::offset_of!(UnityVulkanImage, usage) - 88usize];
    ["Offset of field: UnityVulkanImage::format"]
        [::std::mem::offset_of!(UnityVulkanImage, format) - 92usize];
    ["Offset of field: UnityVulkanImage::extent"]
        [::std::mem::offset_of!(UnityVulkanImage, extent) - 96usize];
    ["Offset of field: UnityVulkanImage::tiling"]
        [::std::mem::offset_of!(UnityVulkanImage, tiling) - 108usize];
    ["Offset of field: UnityVulkanImage::type_"]
        [::std::mem::offset_of!(UnityVulkanImage, type_) - 112usize];
    ["Offset of field: UnityVulkanImage::samples"]
        [::std::mem::offset_of!(UnityVulkanImage, samples) - 116usize];
    ["Offset of field: UnityVulkanImage::layers"]
        [::std::mem::offset_of!(UnityVulkanImage, layers) - 120usize];
    ["Offset of field: UnityVulkanImage::mipCount"]
        [::std::mem::offset_of!(UnityVulkanImage, mipCount) - 124usize];
    ["Offset of field: UnityVulkanImage::reserved"]
        [::std::mem::offset_of!(UnityVulkanImage, reserved) - 128usize];
};
impl Default for UnityVulkanImage {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
#[repr(C)]
#[derive(Copy, Clone)]
pub struct UnityVulkanBuffer {
    pub memory: UnityVulkanMemory,
    pub buffer: VkBuffer,
    pub sizeInBytes: usize,
    pub usage: VkBufferUsageFlags,
    pub reserved: [*mut ::std::os::raw::c_void; 4usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of UnityVulkanBuffer"][::std::mem::size_of::<UnityVulkanBuffer>() - 128usize];
    ["Alignment of UnityVulkanBuffer"][::std::mem::align_of::<UnityVulkanBuffer>() - 8usize];
    ["Offset of field: UnityVulkanBuffer::memory"]
        [::std::mem::offset_of!(UnityVulkanBuffer, memory) - 0usize];
    ["Offset of field: UnityVulkanBuffer::buffer"]
        [::std::mem::offset_of!(UnityVulkanBuffer, buffer) - 72usize];
    ["Offset of field: UnityVulkanBuffer::sizeInBytes"]
        [::std::mem::offset_of!(UnityVulkanBuffer, sizeInBytes) - 80usize];
    ["Offset of field: UnityVulkanBuffer::usage"]
        [::std::mem::offset_of!(UnityVulkanBuffer, usage) - 88usize];
    ["Offset of field: UnityVulkanBuffer::reserved"]
        [::std::mem::offset_of!(UnityVulkanBuffer, reserved) - 96usize];
};
impl Default for UnityVulkanBuffer {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
#[repr(C)]
#[derive(Copy, Clone)]
pub struct UnityVulkanRecordingState {
    pub commandBuffer: VkCommandBuffer,
    pub commandBufferLevel: VkCommandBufferLevel,
    pub renderPass: VkRenderPass,
    pub framebuffer: VkFramebuffer,
    pub subPassIndex: ::std::os::raw::c_int,
    pub currentFrameNumber: ::std::os::raw::c_ulonglong,
    pub safeFrameNumber: ::std::os::raw::c_ulonglong,
    pub reserved: [*mut ::std::os::raw::c_void; 4usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of UnityVulkanRecordingState"]
        [::std::mem::size_of::<UnityVulkanRecordingState>() - 88usize];
    ["Alignment of UnityVulkanRecordingState"]
        [::std::mem::align_of::<UnityVulkanRecordingState>() - 8usize];
    ["Offset of field: UnityVulkanRecordingState::commandBuffer"]
        [::std::mem::offset_of!(UnityVulkanRecordingState, commandBuffer) - 0usize];
    ["Offset of field: UnityVulkanRecordingState::commandBufferLevel"]
        [::std::mem::offset_of!(UnityVulkanRecordingState, commandBufferLevel) - 8usize];
    ["Offset of field: UnityVulkanRecordingState::renderPass"]
        [::std::mem::offset_of!(UnityVulkanRecordingState, renderPass) - 16usize];
    ["Offset of field: UnityVulkanRecordingState::framebuffer"]
        [::std::mem::offset_of!(UnityVulkanRecordingState, framebuffer) - 24usize];
    ["Offset of field: UnityVulkanRecordingState::subPassIndex"]
        [::std::mem::offset_of!(UnityVulkanRecordingState, subPassIndex) - 32usize];
    ["Offset of field: UnityVulkanRecordingState::currentFrameNumber"]
        [::std::mem::offset_of!(UnityVulkanRecordingState, currentFrameNumber) - 40usize];
    ["Offset of field: UnityVulkanRecordingState::safeFrameNumber"]
        [::std::mem::offset_of!(UnityVulkanRecordingState, safeFrameNumber) - 48usize];
    ["Offset of field: UnityVulkanRecordingState::reserved"]
        [::std::mem::offset_of!(UnityVulkanRecordingState, reserved) - 56usize];
};
impl Default for UnityVulkanRecordingState {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
pub const UnityVulkanEventRenderPassPreCondition_kUnityVulkanRenderPass_DontCare:
    UnityVulkanEventRenderPassPreCondition = 0;
pub const UnityVulkanEventRenderPassPreCondition_kUnityVulkanRenderPass_EnsureInside:
    UnityVulkanEventRenderPassPreCondition = 1;
pub const UnityVulkanEventRenderPassPreCondition_kUnityVulkanRenderPass_EnsureOutside:
    UnityVulkanEventRenderPassPreCondition = 2;
pub type UnityVulkanEventRenderPassPreCondition = ::std::os::raw::c_uint;
pub const UnityVulkanGraphicsQueueAccess_kUnityVulkanGraphicsQueueAccess_DontCare:
    UnityVulkanGraphicsQueueAccess = 0;
pub const UnityVulkanGraphicsQueueAccess_kUnityVulkanGraphicsQueueAccess_Allow:
    UnityVulkanGraphicsQueueAccess = 1;
pub type UnityVulkanGraphicsQueueAccess = ::std::os::raw::c_uint;
pub const UnityVulkanEventConfigFlagBits_kUnityVulkanEventConfigFlag_EnsurePreviousFrameSubmission : UnityVulkanEventConfigFlagBits = 1 ;
pub const UnityVulkanEventConfigFlagBits_kUnityVulkanEventConfigFlag_FlushCommandBuffers:
    UnityVulkanEventConfigFlagBits = 2;
pub const UnityVulkanEventConfigFlagBits_kUnityVulkanEventConfigFlag_SyncWorkerThreads:
    UnityVulkanEventConfigFlagBits = 4;
pub const UnityVulkanEventConfigFlagBits_kUnityVulkanEventConfigFlag_ModifiesCommandBuffersState:
    UnityVulkanEventConfigFlagBits = 8;
pub type UnityVulkanEventConfigFlagBits = ::std::os::raw::c_uint;
#[repr(C)]
#[derive(Copy, Clone)]
pub struct UnityVulkanPluginEventConfig {
    pub renderPassPrecondition: UnityVulkanEventRenderPassPreCondition,
    pub graphicsQueueAccess: UnityVulkanGraphicsQueueAccess,
    pub flags: u32,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of UnityVulkanPluginEventConfig"]
        [::std::mem::size_of::<UnityVulkanPluginEventConfig>() - 12usize];
    ["Alignment of UnityVulkanPluginEventConfig"]
        [::std::mem::align_of::<UnityVulkanPluginEventConfig>() - 4usize];
    ["Offset of field: UnityVulkanPluginEventConfig::renderPassPrecondition"]
        [::std::mem::offset_of!(UnityVulkanPluginEventConfig, renderPassPrecondition) - 0usize];
    ["Offset of field: UnityVulkanPluginEventConfig::graphicsQueueAccess"]
        [::std::mem::offset_of!(UnityVulkanPluginEventConfig, graphicsQueueAccess) - 4usize];
    ["Offset of field: UnityVulkanPluginEventConfig::flags"]
        [::std::mem::offset_of!(UnityVulkanPluginEventConfig, flags) - 8usize];
};
impl Default for UnityVulkanPluginEventConfig {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
unsafe extern "system" {
    #[link_name = "\u{1}__ZL21UnityVulkanWholeImage"]
    pub static UnityVulkanWholeImage: *const VkImageSubresource;
}
pub type UnityVulkanInitCallback = ::std::option::Option<
    unsafe extern "system" fn(
        getInstanceProcAddr: PFN_vkGetInstanceProcAddr,
        userdata: *mut ::std::os::raw::c_void,
    ) -> PFN_vkGetInstanceProcAddr,
>;
pub const UnityVulkanSwapchainMode_kUnityVulkanSwapchainMode_Default: UnityVulkanSwapchainMode = 0;
pub const UnityVulkanSwapchainMode_kUnityVulkanSwapchainMode_Offscreen: UnityVulkanSwapchainMode =
    1;
pub type UnityVulkanSwapchainMode = ::std::os::raw::c_uint;
#[repr(C)]
#[derive(Copy, Clone)]
pub struct UnityVulkanSwapchainConfiguration {
    pub mode: UnityVulkanSwapchainMode,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of UnityVulkanSwapchainConfiguration"]
        [::std::mem::size_of::<UnityVulkanSwapchainConfiguration>() - 4usize];
    ["Alignment of UnityVulkanSwapchainConfiguration"]
        [::std::mem::align_of::<UnityVulkanSwapchainConfiguration>() - 4usize];
    ["Offset of field: UnityVulkanSwapchainConfiguration::mode"]
        [::std::mem::offset_of!(UnityVulkanSwapchainConfiguration, mode) - 0usize];
};
impl Default for UnityVulkanSwapchainConfiguration {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
pub const kUnityVulkanInitCallbackMaxPriority: _bindgen_ty_1 = 2147483647;
pub type _bindgen_ty_1 = ::std::os::raw::c_uint;
#[repr(C)]
pub struct IUnityGraphicsVulkanV2 {
    pub InterceptInitialization: ::std::option::Option<
        unsafe extern "system" fn(
            func: UnityVulkanInitCallback,
            userdata: *mut ::std::os::raw::c_void,
        ) -> bool,
    >,
    pub InterceptVulkanAPI: ::std::option::Option<
        unsafe extern "system" fn(
            name: *const ::std::os::raw::c_char,
            func: PFN_vkVoidFunction,
        ) -> PFN_vkVoidFunction,
    >,
    pub ConfigureEvent: ::std::option::Option<
        unsafe extern "system" fn(
            eventID: ::std::os::raw::c_int,
            pluginEventConfig: *const UnityVulkanPluginEventConfig,
        ),
    >,
    pub Instance: ::std::option::Option<unsafe extern "system" fn() -> UnityVulkanInstance>,
    pub CommandRecordingState: ::std::option::Option<
        unsafe extern "system" fn(
            outCommandRecordingState: *mut UnityVulkanRecordingState,
            queueAccess: UnityVulkanGraphicsQueueAccess,
        ) -> bool,
    >,
    pub AccessTexture: ::std::option::Option<
        unsafe extern "system" fn(
            nativeTexture: *mut ::std::os::raw::c_void,
            subResource: *const VkImageSubresource,
            layout: VkImageLayout,
            pipelineStageFlags: VkPipelineStageFlags,
            accessFlags: VkAccessFlags,
            accessMode: UnityVulkanResourceAccessMode,
            outImage: *mut UnityVulkanImage,
        ) -> bool,
    >,
    pub AccessRenderBufferTexture: ::std::option::Option<
        unsafe extern "system" fn(
            nativeRenderBuffer: UnityRenderBuffer,
            subResource: *const VkImageSubresource,
            layout: VkImageLayout,
            pipelineStageFlags: VkPipelineStageFlags,
            accessFlags: VkAccessFlags,
            accessMode: UnityVulkanResourceAccessMode,
            outImage: *mut UnityVulkanImage,
        ) -> bool,
    >,
    pub AccessRenderBufferResolveTexture: ::std::option::Option<
        unsafe extern "system" fn(
            nativeRenderBuffer: UnityRenderBuffer,
            subResource: *const VkImageSubresource,
            layout: VkImageLayout,
            pipelineStageFlags: VkPipelineStageFlags,
            accessFlags: VkAccessFlags,
            accessMode: UnityVulkanResourceAccessMode,
            outImage: *mut UnityVulkanImage,
        ) -> bool,
    >,
    pub AccessBuffer: ::std::option::Option<
        unsafe extern "system" fn(
            nativeBuffer: *mut ::std::os::raw::c_void,
            pipelineStageFlags: VkPipelineStageFlags,
            accessFlags: VkAccessFlags,
            accessMode: UnityVulkanResourceAccessMode,
            outBuffer: *mut UnityVulkanBuffer,
        ) -> bool,
    >,
    pub EnsureOutsideRenderPass: ::std::option::Option<unsafe extern "system" fn()>,
    pub EnsureInsideRenderPass: ::std::option::Option<unsafe extern "system" fn()>,
    pub AccessQueue: ::std::option::Option<
        unsafe extern "system" fn(
            arg1: UnityRenderingEventAndData,
            eventId: ::std::os::raw::c_int,
            userData: *mut ::std::os::raw::c_void,
            flush: bool,
        ),
    >,
    pub ConfigureSwapchain: ::std::option::Option<
        unsafe extern "system" fn(swapChainConfig: *const UnityVulkanSwapchainConfiguration) -> bool,
    >,
    pub AccessTextureByID: ::std::option::Option<
        unsafe extern "system" fn(
            textureID: UnityTextureID,
            subResource: *const VkImageSubresource,
            layout: VkImageLayout,
            pipelineStageFlags: VkPipelineStageFlags,
            accessFlags: VkAccessFlags,
            accessMode: UnityVulkanResourceAccessMode,
            outImage: *mut UnityVulkanImage,
        ) -> bool,
    >,
    pub AddInterceptInitialization: ::std::option::Option<
        unsafe extern "system" fn(
            func: UnityVulkanInitCallback,
            userdata: *mut ::std::os::raw::c_void,
            priority: i32,
        ) -> bool,
    >,
    pub RemoveInterceptInitialization:
        ::std::option::Option<unsafe extern "system" fn(func: UnityVulkanInitCallback) -> bool>,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of IUnityGraphicsVulkanV2"][::std::mem::size_of::<IUnityGraphicsVulkanV2>() - 128usize];
    ["Alignment of IUnityGraphicsVulkanV2"]
        [::std::mem::align_of::<IUnityGraphicsVulkanV2>() - 8usize];
    ["Offset of field: IUnityGraphicsVulkanV2::InterceptInitialization"]
        [::std::mem::offset_of!(IUnityGraphicsVulkanV2, InterceptInitialization) - 0usize];
    ["Offset of field: IUnityGraphicsVulkanV2::InterceptVulkanAPI"]
        [::std::mem::offset_of!(IUnityGraphicsVulkanV2, InterceptVulkanAPI) - 8usize];
    ["Offset of field: IUnityGraphicsVulkanV2::ConfigureEvent"]
        [::std::mem::offset_of!(IUnityGraphicsVulkanV2, ConfigureEvent) - 16usize];
    ["Offset of field: IUnityGraphicsVulkanV2::Instance"]
        [::std::mem::offset_of!(IUnityGraphicsVulkanV2, Instance) - 24usize];
    ["Offset of field: IUnityGraphicsVulkanV2::CommandRecordingState"]
        [::std::mem::offset_of!(IUnityGraphicsVulkanV2, CommandRecordingState) - 32usize];
    ["Offset of field: IUnityGraphicsVulkanV2::AccessTexture"]
        [::std::mem::offset_of!(IUnityGraphicsVulkanV2, AccessTexture) - 40usize];
    ["Offset of field: IUnityGraphicsVulkanV2::AccessRenderBufferTexture"]
        [::std::mem::offset_of!(IUnityGraphicsVulkanV2, AccessRenderBufferTexture) - 48usize];
    ["Offset of field: IUnityGraphicsVulkanV2::AccessRenderBufferResolveTexture"][::std::mem::offset_of!(
        IUnityGraphicsVulkanV2,
        AccessRenderBufferResolveTexture
    ) - 56usize];
    ["Offset of field: IUnityGraphicsVulkanV2::AccessBuffer"]
        [::std::mem::offset_of!(IUnityGraphicsVulkanV2, AccessBuffer) - 64usize];
    ["Offset of field: IUnityGraphicsVulkanV2::EnsureOutsideRenderPass"]
        [::std::mem::offset_of!(IUnityGraphicsVulkanV2, EnsureOutsideRenderPass) - 72usize];
    ["Offset of field: IUnityGraphicsVulkanV2::EnsureInsideRenderPass"]
        [::std::mem::offset_of!(IUnityGraphicsVulkanV2, EnsureInsideRenderPass) - 80usize];
    ["Offset of field: IUnityGraphicsVulkanV2::AccessQueue"]
        [::std::mem::offset_of!(IUnityGraphicsVulkanV2, AccessQueue) - 88usize];
    ["Offset of field: IUnityGraphicsVulkanV2::ConfigureSwapchain"]
        [::std::mem::offset_of!(IUnityGraphicsVulkanV2, ConfigureSwapchain) - 96usize];
    ["Offset of field: IUnityGraphicsVulkanV2::AccessTextureByID"]
        [::std::mem::offset_of!(IUnityGraphicsVulkanV2, AccessTextureByID) - 104usize];
    ["Offset of field: IUnityGraphicsVulkanV2::AddInterceptInitialization"]
        [::std::mem::offset_of!(IUnityGraphicsVulkanV2, AddInterceptInitialization) - 112usize];
    ["Offset of field: IUnityGraphicsVulkanV2::RemoveInterceptInitialization"]
        [::std::mem::offset_of!(IUnityGraphicsVulkanV2, RemoveInterceptInitialization) - 120usize];
};
impl Default for IUnityGraphicsVulkanV2 {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
#[repr(C)]
pub struct IUnityGraphicsVulkan {
    pub InterceptInitialization: ::std::option::Option<
        unsafe extern "system" fn(
            func: UnityVulkanInitCallback,
            userdata: *mut ::std::os::raw::c_void,
        ) -> bool,
    >,
    pub InterceptVulkanAPI: ::std::option::Option<
        unsafe extern "system" fn(
            name: *const ::std::os::raw::c_char,
            func: PFN_vkVoidFunction,
        ) -> PFN_vkVoidFunction,
    >,
    pub ConfigureEvent: ::std::option::Option<
        unsafe extern "system" fn(
            eventID: ::std::os::raw::c_int,
            pluginEventConfig: *const UnityVulkanPluginEventConfig,
        ),
    >,
    pub Instance: ::std::option::Option<unsafe extern "system" fn() -> UnityVulkanInstance>,
    pub CommandRecordingState: ::std::option::Option<
        unsafe extern "system" fn(
            outCommandRecordingState: *mut UnityVulkanRecordingState,
            queueAccess: UnityVulkanGraphicsQueueAccess,
        ) -> bool,
    >,
    pub AccessTexture: ::std::option::Option<
        unsafe extern "system" fn(
            nativeTexture: *mut ::std::os::raw::c_void,
            subResource: *const VkImageSubresource,
            layout: VkImageLayout,
            pipelineStageFlags: VkPipelineStageFlags,
            accessFlags: VkAccessFlags,
            accessMode: UnityVulkanResourceAccessMode,
            outImage: *mut UnityVulkanImage,
        ) -> bool,
    >,
    pub AccessRenderBufferTexture: ::std::option::Option<
        unsafe extern "system" fn(
            nativeRenderBuffer: UnityRenderBuffer,
            subResource: *const VkImageSubresource,
            layout: VkImageLayout,
            pipelineStageFlags: VkPipelineStageFlags,
            accessFlags: VkAccessFlags,
            accessMode: UnityVulkanResourceAccessMode,
            outImage: *mut UnityVulkanImage,
        ) -> bool,
    >,
    pub AccessRenderBufferResolveTexture: ::std::option::Option<
        unsafe extern "system" fn(
            nativeRenderBuffer: UnityRenderBuffer,
            subResource: *const VkImageSubresource,
            layout: VkImageLayout,
            pipelineStageFlags: VkPipelineStageFlags,
            accessFlags: VkAccessFlags,
            accessMode: UnityVulkanResourceAccessMode,
            outImage: *mut UnityVulkanImage,
        ) -> bool,
    >,
    pub AccessBuffer: ::std::option::Option<
        unsafe extern "system" fn(
            nativeBuffer: *mut ::std::os::raw::c_void,
            pipelineStageFlags: VkPipelineStageFlags,
            accessFlags: VkAccessFlags,
            accessMode: UnityVulkanResourceAccessMode,
            outBuffer: *mut UnityVulkanBuffer,
        ) -> bool,
    >,
    pub EnsureOutsideRenderPass: ::std::option::Option<unsafe extern "system" fn()>,
    pub EnsureInsideRenderPass: ::std::option::Option<unsafe extern "system" fn()>,
    pub AccessQueue: ::std::option::Option<
        unsafe extern "system" fn(
            arg1: UnityRenderingEventAndData,
            eventId: ::std::os::raw::c_int,
            userData: *mut ::std::os::raw::c_void,
            flush: bool,
        ),
    >,
    pub ConfigureSwapchain: ::std::option::Option<
        unsafe extern "system" fn(swapChainConfig: *const UnityVulkanSwapchainConfiguration) -> bool,
    >,
    pub AccessTextureByID: ::std::option::Option<
        unsafe extern "system" fn(
            textureID: UnityTextureID,
            subResource: *const VkImageSubresource,
            layout: VkImageLayout,
            pipelineStageFlags: VkPipelineStageFlags,
            accessFlags: VkAccessFlags,
            accessMode: UnityVulkanResourceAccessMode,
            outImage: *mut UnityVulkanImage,
        ) -> bool,
    >,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of IUnityGraphicsVulkan"][::std::mem::size_of::<IUnityGraphicsVulkan>() - 112usize];
    ["Alignment of IUnityGraphicsVulkan"][::std::mem::align_of::<IUnityGraphicsVulkan>() - 8usize];
    ["Offset of field: IUnityGraphicsVulkan::InterceptInitialization"]
        [::std::mem::offset_of!(IUnityGraphicsVulkan, InterceptInitialization) - 0usize];
    ["Offset of field: IUnityGraphicsVulkan::InterceptVulkanAPI"]
        [::std::mem::offset_of!(IUnityGraphicsVulkan, InterceptVulkanAPI) - 8usize];
    ["Offset of field: IUnityGraphicsVulkan::ConfigureEvent"]
        [::std::mem::offset_of!(IUnityGraphicsVulkan, ConfigureEvent) - 16usize];
    ["Offset of field: IUnityGraphicsVulkan::Instance"]
        [::std::mem::offset_of!(IUnityGraphicsVulkan, Instance) - 24usize];
    ["Offset of field: IUnityGraphicsVulkan::CommandRecordingState"]
        [::std::mem::offset_of!(IUnityGraphicsVulkan, CommandRecordingState) - 32usize];
    ["Offset of field: IUnityGraphicsVulkan::AccessTexture"]
        [::std::mem::offset_of!(IUnityGraphicsVulkan, AccessTexture) - 40usize];
    ["Offset of field: IUnityGraphicsVulkan::AccessRenderBufferTexture"]
        [::std::mem::offset_of!(IUnityGraphicsVulkan, AccessRenderBufferTexture) - 48usize];
    ["Offset of field: IUnityGraphicsVulkan::AccessRenderBufferResolveTexture"]
        [::std::mem::offset_of!(IUnityGraphicsVulkan, AccessRenderBufferResolveTexture) - 56usize];
    ["Offset of field: IUnityGraphicsVulkan::AccessBuffer"]
        [::std::mem::offset_of!(IUnityGraphicsVulkan, AccessBuffer) - 64usize];
    ["Offset of field: IUnityGraphicsVulkan::EnsureOutsideRenderPass"]
        [::std::mem::offset_of!(IUnityGraphicsVulkan, EnsureOutsideRenderPass) - 72usize];
    ["Offset of field: IUnityGraphicsVulkan::EnsureInsideRenderPass"]
        [::std::mem::offset_of!(IUnityGraphicsVulkan, EnsureInsideRenderPass) - 80usize];
    ["Offset of field: IUnityGraphicsVulkan::AccessQueue"]
        [::std::mem::offset_of!(IUnityGraphicsVulkan, AccessQueue) - 88usize];
    ["Offset of field: IUnityGraphicsVulkan::ConfigureSwapchain"]
        [::std::mem::offset_of!(IUnityGraphicsVulkan, ConfigureSwapchain) - 96usize];
    ["Offset of field: IUnityGraphicsVulkan::AccessTextureByID"]
        [::std::mem::offset_of!(IUnityGraphicsVulkan, AccessTextureByID) - 104usize];
};
impl Default for IUnityGraphicsVulkan {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
