[workspace]
members = [
    "unity-native-plugin",
    "unity-native-plugin-vulkan",
    "unity-native-plugin-sys",
    "unity-native-plugin-tester",
    "unity-native-plugin-sample",
    "unity-native-plugin-sample-profiler",
]
resolver = "2"

