name: CI

on:
  pull_request:
  push:
    branches: [master]

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: -D warnings

jobs:
  test:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Update Rust toolchain
        run: rustup update stable && rustup default stable && rustup component add clippy

      - name: Clippy
        run: cargo clippy --workspace --all-targets

      - name: Build
        run: cargo build --workspace --all-targets

      - name: Test
        run: cargo test --workspace
